//! Code generation for grammar macros.

mod parser;
mod reduction;
mod table;
mod terminal;

use proc_macro2::TokenStream;
use quote::quote;
use syn::Error;

use crate::ir::GrammarIr;

/// Generate all code for a grammar.
pub fn generate(grammar: &GrammarIr) -> Result<TokenStream, Error> {
    // Build the parse table at compile time
    let table_data = table::build_table(grammar)?;

    // Generate all the code components
    let terminal_enum = terminal::generate(grammar, &table_data);
    // Note: reduction enum is now generated by parser::generate() with constructor functions
    let parser_code = parser::generate(grammar, &table_data);

    let _vis = &grammar.visibility;

    Ok(quote! {
        #terminal_enum
        #parser_code
    })
}
